### ISSUE TITLE
[BUG] Leave a review button not working

### ISSUE THREAD

**Issue by billipo** [roblack/workshop#5]
### iPhone info:
 - Device: [iPhone 13]
 - OS: [e.g. iOS 15]
 - Version [e.g. 1.5]

**Comment by emin-grbo** [comment]
Damn Apple 😂
They limit you to ask for review only 3 times a year.

So, I guess I should make sure not to ask the same user more than 3 times a year. And when you tap once, that is 1 request. 

Then because of the delay which is on their side, you tap again...maybe 2 times, and thats it...one year down the drain 😂 You can almost see this is my first real app 😅

Thank you for reporting this, will try and figure out a better solution for this.

**Comment by emin-grbo** [comment]
Can you reach out to me on twitter, i wanna send you some codes :)

**Comment by billipo** [comment]
Yeah, that sucks about their review limit. I'm sure you'll find a better way to implement.

**Comment by billipo** [comment]
My twitter is @onepixelman. How can I find you on there?

**Comment by billipo** [comment]
You can also just email directly, if you want: billipo @ gmail.com

**Comment by emin-grbo** [comment]
For now this will be removed in 1.6 and enabled with a counter on userside to make sure i don't overdo it 🙌
